name: CI check

on: push

jobs:
  semver-check:
    name: Semver Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"
        run: npm add --global nx@14.0.0 @nrwl/cli@14.0.0

      - name: Generate Tag
        run: |
          SOURCE_BRANCH=${{ github.ref.name }}
          REGEX="^.+\/(feature|release|bugfix)\/.+$"

          if [[ $SOURCE_BRANCH =~ $REGEX ]]; then
            SOURCE_BRANCH_TYPE=${BASH_REMATCH[1]}
            echo "Source branch: $SOURCE_BRANCH"
          else
            echo "Didn`t match branch name"
          fi
