name: CI check

on: push

jobs:
  semver-check:
    name: Semver Check
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Add nx
        run: npm add --global nx@14.0.0 @nrwl/cli@14.0.0

      - name: Some script
        shell: "bash"
        run: |
          commit_subject=$(git log -1 --pretty=format:%s)
          echo "Commit subject: $commit_subject"

          regex='^.+\/(feature|release|bugfix)\/.+$'
          [[ $commit_subject =~ $regex ]]
          branch_name=${BASH_REMATCH[1]}
          echo "Merged branch: $branch_name"

      - name: Generate Tag
        shell: "bash"
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          REGEX="^.+\/(feature|release|bugfix)\/.+$"

          if [[ $COMMIT_MESSAGE =~ $REGEX ]]; then
            SOURCE_BRANCH_TYPE=${BASH_REMATCH[1]}
            echo "Source branch: $SOURCE_BRANCH_TYPE"
          else
            echo "Didn`t match branch name"
          fi
