name: CI check

on: push

jobs:
  semver-check:
    name: Semver Check
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Add nx
        run: npm add --global nx@14.0.0 @nrwl/cli@14.0.0

      - name: Some script
        run: |
          commit_subject=$(git log -1 --pretty=format:%s)
          echo "Commit subject: $commit_subject"

          regex='^.+\/(feature|release|bugfix)\/.+$'

          if [[ $commit_subject =~ $regex ]]; then
            branch_name=${BASH_REMATCH[1]}
            echo "Merged branch: $branch_name"
          fi

      - name: Generate Tag
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          REGEX="^.+\/(feature|release|bugfix)\/.+$"

          if [[ $COMMIT_MESSAGE =~ $REGEX ]]; then
            SOURCE_BRANCH_TYPE=${BASH_REMATCH[1]}
            echo "Source branch: $SOURCE_BRANCH_TYPE"
          else
            echo "Didnt match branch name"
          fi

      - name: Create commit
        run: |
          git config --global user.email "test@user.net" && git config --global user.name "System User"

          # sed -i "s/release: test-fe@[A-Za-z0-9+-.]*'/release: 'test-fe@T1.2.3'/" star-wars/src/environments/environment.ts
          git add star-wars/src/environments/environment.ts

          git commit -m "Testing commit addition"

          git push
          git push origin 'v0.1.3'

      # - name: Push Tag
      #   run: |
      #     git push origin 'v0.1.3'
