name: CI check

on: push

jobs:
  semver-check:
    name: Semver Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Add nx
        run: npm add --global nx@14.0.0 @nrwl/cli@14.0.0

      - name: Generate Tag
        shell: "bash"
        run: |
          echo '${{ github.event_name }} , ref.name is ${{ github.ref_name }}, head ref: ${{ github.head_ref }}'
          # REGEX="^.+\/(feature|release|bugfix)\/.+$"

          # if [[ $SOURCE_BRANCH =~ $REGEX ]]; then
          #   # SOURCE_BRANCH_TYPE=${BASH_REMATCH[1]}
          #   echo "Source branch: $SOURCE_BRANCH"
          # else
          #   echo "Didn`t match branch name"
          # fi
